//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 07:24:40 PM IDT 
//


package org.jenkinsci.plugins.projectConfiguration.devices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jenkinsci.plugins.projectConfiguration.devices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jenkinsci.plugins.projectConfiguration.devices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link Unit.Slots }
     * 
     */
    public Unit.Slots createUnitSlots() {
        return new Unit.Slots();
    }

    /**
     * Create an instance of {@link Unit.Slots.Slot }
     * 
     */
    public Unit.Slots.Slot createUnitSlotsSlot() {
        return new Unit.Slots.Slot();
    }

    /**
     * Create an instance of {@link Unit.Slots.Slot.SlotDesc }
     * 
     */
    public Unit.Slots.Slot.SlotDesc createUnitSlotsSlotSlotDesc() {
        return new Unit.Slots.Slot.SlotDesc();
    }

    /**
     * Create an instance of {@link Unit.Slots.Slot.SlotDesc.Links }
     * 
     */
    public Unit.Slots.Slot.SlotDesc.Links createUnitSlotsSlotSlotDescLinks() {
        return new Unit.Slots.Slot.SlotDesc.Links();
    }

    /**
     * Create an instance of {@link Unit.WatchFiles }
     * 
     */
    public Unit.WatchFiles createUnitWatchFiles() {
        return new Unit.WatchFiles();
    }

    /**
     * Create an instance of {@link Unit.Slots.Slot.SlotDesc.Links.Link }
     * 
     */
    public Unit.Slots.Slot.SlotDesc.Links.Link createUnitSlotsSlotSlotDescLinksLink() {
        return new Unit.Slots.Slot.SlotDesc.Links.Link();
    }

}
