//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 07:24:40 PM IDT 
//


package org.jenkinsci.plugins.projectConfiguration.devices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnitType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WatchFiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="WatchFile" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TelnetUnitIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ComOverTelnetIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ComOverTelnetPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SerialPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RootPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClishUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SWVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Chassis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DevelopmentVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitConfigFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Slots">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Slot" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SlotDesc">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Card" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Links">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Link" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitType",
    "watchFiles",
    "telnetUnitIP",
    "comOverTelnetIP",
    "comOverTelnetPort",
    "serialPort",
    "rootPassword",
    "clishUser",
    "swVersion",
    "chassis",
    "developmentVersion",
    "unitConfigFile",
    "slots"
})
@XmlRootElement(name = "Unit")
public class Unit {

    @XmlElement(name = "UnitType", required = true)
    protected String unitType;
    @XmlElement(name = "WatchFiles", required = true)
    protected Unit.WatchFiles watchFiles;
    @XmlElement(name = "TelnetUnitIP", required = true)
    protected String telnetUnitIP;
    @XmlElement(name = "ComOverTelnetIP", required = true)
    protected String comOverTelnetIP;
    @XmlElement(name = "ComOverTelnetPort", required = true)
    protected String comOverTelnetPort;
    @XmlElement(name = "SerialPort", required = true)
    protected String serialPort;
    @XmlElement(name = "RootPassword", required = true)
    protected String rootPassword;
    @XmlElement(name = "ClishUser", required = true)
    protected String clishUser;
    @XmlElement(name = "SWVersion", required = true)
    protected String swVersion;
    @XmlElement(name = "Chassis", required = true)
    protected String chassis;
    @XmlElement(name = "DevelopmentVersion", required = true)
    protected String developmentVersion;
    @XmlElement(name = "UnitConfigFile", required = true)
    protected String unitConfigFile;
    @XmlElement(name = "Slots", required = true)
    protected Unit.Slots slots;

    /**
     * Gets the value of the unitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitType(String value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the watchFiles property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.WatchFiles }
     *     
     */
    public Unit.WatchFiles getWatchFiles() {
        return watchFiles;
    }

    /**
     * Sets the value of the watchFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.WatchFiles }
     *     
     */
    public void setWatchFiles(Unit.WatchFiles value) {
        this.watchFiles = value;
    }

    /**
     * Gets the value of the telnetUnitIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelnetUnitIP() {
        return telnetUnitIP;
    }

    /**
     * Sets the value of the telnetUnitIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelnetUnitIP(String value) {
        this.telnetUnitIP = value;
    }

    /**
     * Gets the value of the comOverTelnetIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComOverTelnetIP() {
        return comOverTelnetIP;
    }

    /**
     * Sets the value of the comOverTelnetIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComOverTelnetIP(String value) {
        this.comOverTelnetIP = value;
    }

    /**
     * Gets the value of the comOverTelnetPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComOverTelnetPort() {
        return comOverTelnetPort;
    }

    /**
     * Sets the value of the comOverTelnetPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComOverTelnetPort(String value) {
        this.comOverTelnetPort = value;
    }

    /**
     * Gets the value of the serialPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialPort() {
        return serialPort;
    }

    /**
     * Sets the value of the serialPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialPort(String value) {
        this.serialPort = value;
    }

    /**
     * Gets the value of the rootPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootPassword() {
        return rootPassword;
    }

    /**
     * Sets the value of the rootPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootPassword(String value) {
        this.rootPassword = value;
    }

    /**
     * Gets the value of the clishUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClishUser() {
        return clishUser;
    }

    /**
     * Sets the value of the clishUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClishUser(String value) {
        this.clishUser = value;
    }

    /**
     * Gets the value of the swVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWVersion() {
        return swVersion;
    }

    /**
     * Sets the value of the swVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWVersion(String value) {
        this.swVersion = value;
    }

    /**
     * Gets the value of the chassis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChassis() {
        return chassis;
    }

    /**
     * Sets the value of the chassis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChassis(String value) {
        this.chassis = value;
    }

    /**
     * Gets the value of the developmentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevelopmentVersion() {
        return developmentVersion;
    }

    /**
     * Sets the value of the developmentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevelopmentVersion(String value) {
        this.developmentVersion = value;
    }

    /**
     * Gets the value of the unitConfigFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitConfigFile() {
        return unitConfigFile;
    }

    /**
     * Sets the value of the unitConfigFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitConfigFile(String value) {
        this.unitConfigFile = value;
    }

    /**
     * Gets the value of the slots property.
     * 
     * @return
     *     possible object is
     *     {@link Unit.Slots }
     *     
     */
    public Unit.Slots getSlots() {
        return slots;
    }

    /**
     * Sets the value of the slots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit.Slots }
     *     
     */
    public void setSlots(Unit.Slots value) {
        this.slots = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Slot" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SlotDesc">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Card" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Links">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Link" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "slot"
    })
    public static class Slots {

        @XmlElement(name = "Slot")
        protected List<Unit.Slots.Slot> slot;

        /**
         * Gets the value of the slot property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the slot property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSlot().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Unit.Slots.Slot }
         * 
         * 
         */
        public List<Unit.Slots.Slot> getSlot() {
            if (slot == null) {
                slot = new ArrayList<Unit.Slots.Slot>();
            }
            return this.slot;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SlotDesc">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Card" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Links">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Link" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "slotDesc"
        })
        public static class Slot {

            @XmlElement(name = "Id", required = true)
            protected String id;
            @XmlElement(name = "SlotDesc", required = true)
            protected Unit.Slots.Slot.SlotDesc slotDesc;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the slotDesc property.
             * 
             * @return
             *     possible object is
             *     {@link Unit.Slots.Slot.SlotDesc }
             *     
             */
            public Unit.Slots.Slot.SlotDesc getSlotDesc() {
                return slotDesc;
            }

            /**
             * Sets the value of the slotDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link Unit.Slots.Slot.SlotDesc }
             *     
             */
            public void setSlotDesc(Unit.Slots.Slot.SlotDesc value) {
                this.slotDesc = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Card" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Links">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Link" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "card",
                "links"
            })
            public static class SlotDesc {

                @XmlElement(name = "Card", required = true)
                protected String card;
                @XmlElement(name = "Links", required = true)
                protected Unit.Slots.Slot.SlotDesc.Links links;

                /**
                 * Gets the value of the card property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCard() {
                    return card;
                }

                /**
                 * Sets the value of the card property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCard(String value) {
                    this.card = value;
                }

                /**
                 * Gets the value of the links property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Unit.Slots.Slot.SlotDesc.Links }
                 *     
                 */
                public Unit.Slots.Slot.SlotDesc.Links getLinks() {
                    return links;
                }

                /**
                 * Sets the value of the links property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Unit.Slots.Slot.SlotDesc.Links }
                 *     
                 */
                public void setLinks(Unit.Slots.Slot.SlotDesc.Links value) {
                    this.links = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Link" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "link"
                })
                public static class Links {

                    @XmlElement(name = "Link")
                    protected List<Unit.Slots.Slot.SlotDesc.Links.Link> link;

                    /**
                     * Gets the value of the link property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the link property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getLink().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Unit.Slots.Slot.SlotDesc.Links.Link }
                     * 
                     * 
                     */
                    public List<Unit.Slots.Slot.SlotDesc.Links.Link> getLink() {
                        if (link == null) {
                            link = new ArrayList<Unit.Slots.Slot.SlotDesc.Links.Link>();
                        }
                        return this.link;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "id",
                        "type"
                    })
                    public static class Link {

                        @XmlElement(name = "Id", required = true)
                        protected String id;
                        @XmlElement(name = "Type", required = true)
                        protected String type;

                        /**
                         * Gets the value of the id property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getId() {
                            return id;
                        }

                        /**
                         * Sets the value of the id property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setId(String value) {
                            this.id = value;
                        }

                        /**
                         * Gets the value of the type property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getType() {
                            return type;
                        }

                        /**
                         * Sets the value of the type property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setType(String value) {
                            this.type = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="WatchFile" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "watchFile"
    })
    public static class WatchFiles {

        @XmlElement(name = "WatchFile")
        protected List<String> watchFile;

        /**
         * Gets the value of the watchFile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the watchFile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWatchFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getWatchFile() {
            if (watchFile == null) {
                watchFile = new ArrayList<String>();
            }
            return this.watchFile;
        }

    }

}
